version: '3'

services:
  opi-db:
    build:
      context: ./postgis
      dockerfile: Dockerfile
    command: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "55432:5432"
    volumes:
      - ~/opi-db:/var/lib/postgresql/data
  opi-backend:
    build:
      context: ..
      dockerfile: docker/back/Dockerfile
    command: pipenv run uvicorn --host 0.0.0.0 --port 8000 app.main:app --reload
    volumes:
      - ../service:/app
    ports:
      - "8000:8000"
    depends_on:
      - opi-db
  opi-frontend:
    build:
      context: ..
      dockerfile: docker/front/Dockerfile
    volumes:
      - ../webapp:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
volumes:
  opi-db: